# Generated by Django 3.2.21 on 2023-11-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='movies')),
                ('categor', models.CharField(choices=[('ACTION', 'ACTION'), ('DRAMA', 'DRAMA'), ('COMEDY', 'COMEDY'), ('ROMANCE', 'ROMANCE'), ('AGASOBANUYE', 'AGASOBANUYE')], max_length=11)),
                ('language', models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('FRANCE', 'FRANCE'), ('KINYARWANDA', 'KINYARWANDA')], max_length=11)),
                ('status', models.CharField(choices=[('RECRNITLY ADDED ', 'RECRNITLY ADDED'), ('MOST WATCHED', 'MOST WATCHED'), ('TOP RATED', 'TOP RATED')], max_length=16)),
                ('year_of_product', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('video', models.FileField(upload_to='video/')),
            ],
        ),
        migrations.CreateModel(
            name='tv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
